# Generated by Django 4.2.2 on 2023-06-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caretaker', '0001_initial'),
        ('lookup', '0001_initial'),
        ('accounts', '0002_accounts_delete_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('weight', models.IntegerField()),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('caretaker_id', models.ForeignKey(db_column='caretaker_id', on_delete=django.db.models.deletion.CASCADE, to='caretaker.caretaker')),
                ('gender', models.ForeignKey(db_column='gender', on_delete=django.db.models.deletion.CASCADE, to='lookup.lookup')),
            ],
            options={
                'db_table': 'Patients ',
            },
        ),
    ]
