# Generated by Django 4.2.2 on 2023-06-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.lookup')),
            ],
            options={
                'db_table': 'Accounts',
            },
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
