# Generated by Django 4.2.2 on 2023-06-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('act_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Activities',
            },
        ),
    ]
