# Generated by Django 4.2.2 on 2023-06-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caretaker', '0001_initial'),
        ('activities', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('act_id', models.ForeignKey(db_column='act_id', on_delete=django.db.models.deletion.CASCADE, to='activities.activities')),
                ('caretaker_id', models.ForeignKey(db_column='caretaker_id', on_delete=django.db.models.deletion.CASCADE, to='caretaker.caretaker')),
                ('pat_id', models.ForeignKey(db_column='pat_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
            options={
                'db_table': 'Activity_Logs',
            },
        ),
    ]
