# Generated by Django 4.2.2 on 2023-06-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.ForeignKey(db_column='gender', on_delete=django.db.models.deletion.CASCADE, to='lookup.lookup')),
            ],
            options={
                'db_table': 'Caretaker',
            },
        ),
    ]
